<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Species;
use Illuminate\Support\Str;

class SpeciesSeeder extends Seeder
{
    public function run(): void
    {
        $species = [
            [
                'name' => 'Enhalus acoroides',
                'local_name' => 'Lamun Besar / Setul',
                'family' => 'Hydrocharitaceae',
                'order' => 'Alismatales',
                'slug' => 'enhalus-acoroides',
                'description' => 'Enhalus acoroides adalah spesies lamun terbesar yang ditemukan di perairan Indo-Pasifik. Spesies ini memiliki peran ekologis yang sangat penting sebagai habitat utama bagi berbagai biota laut termasuk dugong dan penyu hijau. Daun panjangnya yang seperti pita membentuk kanopi tebal yang berfungsi sebagai penangkap sedimen alami dan pelindung garis pantai dari erosi.',
                'morphology' => 'Daun berbentuk pita panjang, lebar 1.2-2 cm, panjang 30-150 cm. Akar dan rhizoma tebal dan kuat. Bunga muncul di permukaan air. Buah berbentuk bulat telur berukuran 3-5 cm.',
                'habitat' => 'Perairan dangkal dengan substrat berpasir hingga berlumpur. Sering ditemukan di zona intertidal hingga subtidal pada kedalaman 0.5-6 meter. Toleran terhadap variasi salinitas.',
                'depth_range_min' => 0.5,
                'depth_range_max' => 6.0,
                'iucn_status' => 'LC',
                'carbon_factor' => 0.061000,
                'is_active' => true,
            ],
            [
                'name' => 'Thalassia hemprichii',
                'local_name' => 'Lamun Sisik Penyu',
                'family' => 'Hydrocharitaceae',
                'order' => 'Alismatales',
                'slug' => 'thalassia-hemprichii',
                'description' => 'Thalassia hemprichii adalah salah satu spesies lamun yang paling umum dan dominan di perairan tropis Indo-Pasifik. Dikenal juga sebagai "lamun sisik penyu" karena bentuk daunnya yang menyerupai sisik. Spesies ini sering menjadi indikator utama kesehatan padang lamun di Indonesia.',
                'morphology' => 'Daun berbentuk pita dengan ujung membulat, lebar 0.4-1 cm, panjang 10-40 cm. Rhizoma beruas dengan bekas daun yang terlihat jelas. Memiliki 2-6 helai daun per tunas.',
                'habitat' => 'Perairan tropis dangkal dengan substrat pasir dan pasir berlumpur. Umum ditemukan di zona subtidal dengan arus sedang. Sering tumbuh bersama spesies lamun lainnya membentuk padang campuran.',
                'depth_range_min' => 0.5,
                'depth_range_max' => 5.0,
                'iucn_status' => 'LC',
                'carbon_factor' => 0.058000,
                'is_active' => true,
            ],
            [
                'name' => 'Cymodocea rotundata',
                'local_name' => 'Lamun Bulat',
                'family' => 'Cymodoceaceae',
                'order' => 'Alismatales',
                'slug' => 'cymodocea-rotundata',
                'description' => 'Cymodocea rotundata adalah spesies lamun berukuran sedang yang tersebar luas di kawasan Indo-Pasifik Barat. Spesies ini sering membentuk padang campuran bersama Thalassia hemprichii dan Halodule uninervis. Berperan penting dalam stabilisasi sedimen dasar laut.',
                'morphology' => 'Daun berbentuk pita dengan ujung membulat, lebar 0.2-0.4 cm, panjang 7-15 cm. Rhizoma halus dengan internodus pendek. Tepi daun halus tanpa gerigi.',
                'habitat' => 'Zona subtidal dangkal dengan substrat berpasir. Toleran terhadap berbagai kondisi lingkungan. Sering ditemukan di laguna dan teluk terlindung.',
                'depth_range_min' => 0.5,
                'depth_range_max' => 4.0,
                'iucn_status' => 'LC',
                'carbon_factor' => 0.052000,
                'is_active' => true,
            ],
            [
                'name' => 'Cymodocea serrulata',
                'local_name' => 'Lamun Gerigi',
                'family' => 'Cymodoceaceae',
                'order' => 'Alismatales',
                'slug' => 'cymodocea-serrulata',
                'description' => 'Cymodocea serrulata dapat dibedakan dari C. rotundata melalui tepi daun bergerigi halus dan ujung daun yang meruncing. Spesies ini memiliki distribusi yang luas dari Afrika Timur hingga Pasifik Barat.',
                'morphology' => 'Daun berbentuk pita dengan tepi bergerigi halus dan ujung meruncing, lebar 0.4-0.9 cm, panjang 5-15 cm. Rhizoma agak tebal. Selubung daun persisten.',
                'habitat' => 'Substrat berpasir hingga berlumpur di perairan dangkal yang terlindung. Dapat ditemukan di laguna, teluk, dan di belakang terumbu karang.',
                'depth_range_min' => 0.5,
                'depth_range_max' => 6.0,
                'iucn_status' => 'LC',
                'carbon_factor' => 0.054000,
                'is_active' => true,
            ],
            [
                'name' => 'Halophila ovalis',
                'local_name' => 'Lamun Oval',
                'family' => 'Hydrocharitaceae',
                'order' => 'Alismatales',
                'slug' => 'halophila-ovalis',
                'description' => 'Halophila ovalis adalah spesies lamun pionir yang paling tersebar luas di dunia. Mampu mengkolonisasi habitat baru dengan cepat dan toleran terhadap berbagai kondisi lingkungan. Sering menjadi spesies pertama yang muncul setelah gangguan ekosistem.',
                'morphology' => 'Daun berbentuk oval-elips, lebar 0.5-2.5 cm, panjang 1-4 cm. Memiliki 2 helai daun per node. Tangkai daun panjang 1-6 cm. Rhizoma tipis dan rapuh.',
                'habitat' => 'Sangat adaptif terhadap berbagai substrat dan kedalaman. Ditemukan dari zona intertidal hingga kedalaman 15 meter. Toleran terhadap kekeruhan tinggi.',
                'depth_range_min' => 0.5,
                'depth_range_max' => 15.0,
                'iucn_status' => 'LC',
                'carbon_factor' => 0.048000,
                'is_active' => true,
            ],
            [
                'name' => 'Halophila minor',
                'local_name' => 'Lamun Oval Kecil',
                'family' => 'Hydrocharitaceae',
                'order' => 'Alismatales',
                'slug' => 'halophila-minor',
                'description' => 'Halophila minor merupakan spesies lamun berukuran kecil yang mirip dengan H. ovalis namun memiliki daun yang lebih kecil dan urat daun yang lebih sedikit. Sering ditemukan di perairan yang lebih dalam.',
                'morphology' => 'Daun berbentuk oval kecil, lebar 0.3-1 cm, panjang 0.5-2.5 cm. Memiliki 4-6 pasang urat daun menyirip. Rhizoma sangat halus.',
                'habitat' => 'Perairan jernih dengan substrat berpasir halus. Cenderung menempati area yang lebih dalam dibanding H. ovalis.',
                'depth_range_min' => 1.0,
                'depth_range_max' => 8.0,
                'iucn_status' => 'LC',
                'carbon_factor' => 0.045000,
                'is_active' => true,
            ],
            [
                'name' => 'Halophila spinulosa',
                'local_name' => 'Lamun Duri',
                'family' => 'Hydrocharitaceae',
                'order' => 'Alismatales',
                'slug' => 'halophila-spinulosa',
                'description' => 'Halophila spinulosa memiliki ciri khas berupa daun-daun kecil yang tersusun menyirip sepanjang batang, menyerupai daun pakis. Spesies ini relatif jarang ditemukan dibanding Halophila lainnya.',
                'morphology' => 'Daun tersusun menyirip pada tangkai daun bercabang, setiap daun kecil berukuran 0.5-1 cm dengan tepi bergerigi halus. Struktur daun menyerupai bulu.',
                'habitat' => 'Perairan subtidal dengan substrat berpasir halus hingga berlumpur. Cenderung menempati perairan yang lebih dalam.',
                'depth_range_min' => 2.0,
                'depth_range_max' => 15.0,
                'iucn_status' => 'DD',
                'carbon_factor' => 0.046000,
                'is_active' => true,
            ],
            [
                'name' => 'Halophila decipiens',
                'local_name' => 'Lamun Tipis',
                'family' => 'Hydrocharitaceae',
                'order' => 'Alismatales',
                'slug' => 'halophila-decipiens',
                'description' => 'Halophila decipiens adalah spesies lamun yang memiliki distribusi terluas di dunia dan mampu hidup di kedalaman paling besar dibanding spesies lamun lainnya. Spesies ini ditemukan di semua lautan tropis dan subtropis.',
                'morphology' => 'Daun berbentuk oval transparan, lebar 0.3-1.2 cm, panjang 1-2.5 cm. Tepi daun bergerigi sangat halus (perlu lensa untuk melihat). Rhizoma sangat tipis.',
                'habitat' => 'Perairan dalam hingga 30 meter dengan intensitas cahaya rendah. Substrat berpasir halus. Salah satu lamun terdalam yang pernah ditemukan.',
                'depth_range_min' => 2.0,
                'depth_range_max' => 30.0,
                'iucn_status' => 'LC',
                'carbon_factor' => 0.043000,
                'is_active' => true,
            ],
            [
                'name' => 'Halodule uninervis',
                'local_name' => 'Lamun Jarum',
                'family' => 'Cymodoceaceae',
                'order' => 'Alismatales',
                'slug' => 'halodule-uninervis',
                'description' => 'Halodule uninervis adalah spesies lamun kecil yang sangat umum ditemukan di seluruh perairan tropis Indonesia. Memiliki toleransi yang tinggi terhadap perubahan salinitas sehingga sering ditemukan di muara sungai.',
                'morphology' => 'Daun berbentuk pita sempit seperti jarum, lebar 0.1-0.35 cm, panjang 5-15 cm. Ujung daun tumpul dengan tiga tonjolan kecil (tridentate). Rhizoma halus.',
                'habitat' => 'Substrat berpasir di zona intertidal dan subtidal dangkal. Toleran terhadap fluktuasi salinitas tinggi. Sering membentuk padang monospecific.',
                'depth_range_min' => 0.5,
                'depth_range_max' => 6.0,
                'iucn_status' => 'LC',
                'carbon_factor' => 0.050000,
                'is_active' => true,
            ],
            [
                'name' => 'Halodule pinifolia',
                'local_name' => 'Lamun Pinus',
                'family' => 'Cymodoceaceae',
                'order' => 'Alismatales',
                'slug' => 'halodule-pinifolia',
                'description' => 'Halodule pinifolia mirip dengan H. uninervis namun memiliki daun yang lebih sempit dan ujung daun yang membulat. Nama "pinus" merujuk pada kemiripan daunnya dengan daun pinus.',
                'morphology' => 'Daun sangat sempit seperti benang, lebar 0.05-0.15 cm, panjang 5-12 cm. Ujung daun membulat (rounded tip). Rhizoma sangat halus dan rapuh.',
                'habitat' => 'Zona intertidal dengan substrat berpasir halus. Sering ditemukan di area dengan paparan sinar matahari langsung.',
                'depth_range_min' => 0.5,
                'depth_range_max' => 4.0,
                'iucn_status' => 'LC',
                'carbon_factor' => 0.049000,
                'is_active' => true,
            ],
            [
                'name' => 'Syringodium isoetifolium',
                'local_name' => 'Lamun Silinder',
                'family' => 'Cymodoceaceae',
                'order' => 'Alismatales',
                'slug' => 'syringodium-isoetifolium',
                'description' => 'Syringodium isoetifolium unik karena memiliki daun berbentuk silinder (terete/tubular), berbeda dari semua spesies lamun lainnya yang berdaun pipih. Spesies ini mudah dikenali di lapangan berkat morfologi daunnya yang khas.',
                'morphology' => 'Daun berbentuk silinder (terete), diameter 0.1-0.2 cm, panjang 7-30 cm. Memiliki 2-3 helai daun per tunas. Rhizoma agak tebal dengan internodus pendek.',
                'habitat' => 'Substrat berpasir hingga pasir berlumpur di perairan dangkal yang terlindung. Sering tumbuh bercampur dengan Cymodocea dan Thalassia.',
                'depth_range_min' => 0.5,
                'depth_range_max' => 6.0,
                'iucn_status' => 'LC',
                'carbon_factor' => 0.055000,
                'is_active' => true,
            ],
            [
                'name' => 'Thalassodendron ciliatum',
                'local_name' => 'Lamun Sabit',
                'family' => 'Cymodoceaceae',
                'order' => 'Alismatales',
                'slug' => 'thalassodendron-ciliatum',
                'description' => 'Thalassodendron ciliatum adalah spesies lamun yang unik karena memiliki batang tegak yang bercabang, berbeda dari kebanyakan lamun lainnya. Spesies ini memiliki potensi penyerapan karbon tertinggi di antara lamun tropis.',
                'morphology' => 'Batang tegak bercabang setinggi 10-20 cm. Daun berbentuk sabit (falcate), lebar 0.4-0.7 cm, panjang 5-15 cm, dengan tepi bergerigi. Rhizoma kayu tebal.',
                'habitat' => 'Substrat keras (karang mati, batuan) di zona subtidal. Tahan terhadap arus dan gelombang kuat. Sering ditemukan di terumbu karang.',
                'depth_range_min' => 1.0,
                'depth_range_max' => 10.0,
                'iucn_status' => 'LC',
                'carbon_factor' => 0.065000,
                'is_active' => true,
            ],
            [
                'name' => 'Ruppia maritima',
                'local_name' => 'Lamun Air Payau',
                'family' => 'Ruppiaceae',
                'order' => 'Alismatales',
                'slug' => 'ruppia-maritima',
                'description' => 'Ruppia maritima adalah satu-satunya spesies lamun yang mampu hidup di air payau hingga air tawar. Spesies ini memiliki distribusi kosmopolitan dan sering ditemukan di laguna pantai dan muara sungai.',
                'morphology' => 'Daun sangat sempit seperti benang, lebar <0.1 cm, panjang 5-10 cm. Batang bercabang-cabang tipis. Bunga kecil tersembunyi dalam selubung.',
                'habitat' => 'Air payau dan laguna pantai dengan salinitas bervariasi (0-70 ppt). Substrat berlumpur. Mampu hidup di air hampir tawar.',
                'depth_range_min' => 0.0,
                'depth_range_max' => 2.0,
                'iucn_status' => 'LC',
                'carbon_factor' => 0.040000,
                'is_active' => true,
            ],
            [
                'name' => 'Zostera japonica',
                'local_name' => 'Lamun Jepang',
                'family' => 'Zosteraceae',
                'order' => 'Alismatales',
                'slug' => 'zostera-japonica',
                'description' => 'Zostera japonica adalah spesies lamun subtropis yang juga ditemukan di beberapa perairan Indonesia bagian utara. Spesies ini relatif lebih jarang ditemukan di perairan tropis.',
                'morphology' => 'Daun berbentuk pita tipis, lebar 0.1-0.3 cm, panjang 10-30 cm. Ujung daun membulat. Rhizoma tipis dengan internodus pendek.',
                'habitat' => 'Zona intertidal dengan substrat berlumpur hingga berpasir. Lebih umum di perairan subtropis. Di Indonesia ditemukan di perairan utara.',
                'depth_range_min' => 0.0,
                'depth_range_max' => 3.0,
                'iucn_status' => 'LC',
                'carbon_factor' => 0.042000,
                'is_active' => true,
            ],
            [
                'name' => 'Halophila sulawesii',
                'local_name' => 'Lamun Sulawesi',
                'family' => 'Hydrocharitaceae',
                'order' => 'Alismatales',
                'slug' => 'halophila-sulawesii',
                'description' => 'Halophila sulawesii adalah spesies lamun endemik yang pertama kali dideskripsikan dari perairan Sulawesi, Indonesia pada tahun 2007. Spesies ini sangat langka dan memerlukan perhatian konservasi khusus.',
                'morphology' => 'Daun berbentuk oval-lanset, lebar 0.5-1.5 cm, panjang 1-3 cm. Memiliki 8-12 pasang urat daun menyirip. Tepi daun halus. Tangkai daun pendek.',
                'habitat' => 'Perairan jernih di sekitar Sulawesi dan pulau-pulau terdekat. Substrat berpasir di kedalaman 1-8 meter. Endemik Indonesia.',
                'depth_range_min' => 1.0,
                'depth_range_max' => 8.0,
                'iucn_status' => 'VU',
                'carbon_factor' => 0.044000,
                'is_active' => true,
            ],
        ];

        foreach ($species as $data) {
            Species::create($data);
        }

        $this->command->info('15 spesies lamun Indonesia berhasil di-seed.');
    }
}
